# tests/test_edgar_facts.py
import pandas as pd
import pytest

from shortlist.providers._edgar_facts import extract_financials, EdgarFinancials


def _cashflow_df():
    # Faithful mirror of edgartools cashflow_statement().to_dataframe(): includes the
    # non-FY columns (concept/label/level/abstract) and ABSOLUTE-USD values, newest FY first.
    return pd.DataFrame([
        {"concept": "us-gaap_NetCashProvided...", "label": "Cash generated by operating activities",
         "standard_concept": "NetCashFromOperatingActivities", "level": 1, "abstract": False,
         "2025-09-27 (FY)": 111_482_000_000.0, "2024-09-28 (FY)": 118_254_000_000.0, "2023-09-30 (FY)": 110_543_000_000.0},
        {"concept": "us-gaap_PaymentsToAcquire...", "label": "Payments for acquisition of PP&E",
         "standard_concept": "CapitalExpenses", "level": 2, "abstract": False,
         "2025-09-27 (FY)": -12_715_000_000.0, "2024-09-28 (FY)": -9_447_000_000.0, "2023-09-30 (FY)": -10_959_000_000.0},
    ])


def _income_df():
    return pd.DataFrame([
        {"concept": "us-gaap_Revenue", "label": "Net sales", "standard_concept": "Revenue", "level": 0, "abstract": False,
         "2025-09-27 (FY)": 416_161_000_000.0, "2024-09-28 (FY)": 391_035_000_000.0, "2023-09-30 (FY)": 383_285_000_000.0},
        {"concept": "us-gaap_NetIncomeLoss", "label": "Net income", "standard_concept": "NetIncomeLoss", "level": 0, "abstract": False,
         "2025-09-27 (FY)": 112_010_000_000.0, "2024-09-28 (FY)": 93_736_000_000.0, "2023-09-30 (FY)": 96_995_000_000.0},
        {"concept": float("nan"), "label": "Diluted (in dollars per share)", "standard_concept": float("nan"), "level": 2, "abstract": False,
         "2025-09-27 (FY)": 7.46, "2024-09-28 (FY)": 6.08, "2023-09-30 (FY)": 6.13},
    ])


def _income_df_with_diluted_shares():
    df = _income_df()
    shares = pd.DataFrame([
        {"concept": "us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding",
         "label": "Weighted-average shares outstanding, diluted", "standard_concept": float("nan"),
         "level": 2, "abstract": False,
         "2025-09-27 (FY)": 15_000_000_000.0, "2024-09-28 (FY)": 15_400_000_000.0,
         "2023-09-30 (FY)": 15_800_000_000.0},
    ])
    return pd.concat([df, shares], ignore_index=True)


def test_diluted_shares_series_extracted_newest_first():
    fin = extract_financials(_income_df_with_diluted_shares(), _cashflow_df(), pd.DataFrame(), shares_diluted=None)
    assert fin.diluted_shares == [15_000_000_000.0, 15_400_000_000.0, 15_800_000_000.0]
    # The per-share EPS row must NOT be mistaken for the share-count row.
    assert fin.diluted_eps == [7.46, 6.08, 6.13]


def test_diluted_shares_empty_when_only_per_share_row_present():
    # _income_df has the diluted EPS (per-share) row but no share-COUNT row.
    fin = extract_financials(_income_df(), _cashflow_df(), pd.DataFrame(), shares_diluted=None)
    assert fin.diluted_shares == []


def test_diluted_shares_matches_used_in_computing_per_share_count_row():
    # A common filer phrasing: the COUNT row whose label embeds "per share". It must
    # still match (it is a share count, not a $/share value) — the plural "shares"
    # distinguishes it from the EPS value row "Diluted (in dollars per share)".
    df = _income_df()
    df = pd.concat([df, pd.DataFrame([
        {"concept": "us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding",
         "label": "Shares used in computing diluted earnings per share",
         "standard_concept": float("nan"), "level": 2, "abstract": False,
         "2025-09-27 (FY)": 15_000_000_000.0, "2024-09-28 (FY)": 15_400_000_000.0,
         "2023-09-30 (FY)": 15_800_000_000.0}])], ignore_index=True)
    fin = extract_financials(df, _cashflow_df(), pd.DataFrame(), shares_diluted=None)
    assert fin.diluted_shares == [15_000_000_000.0, 15_400_000_000.0, 15_800_000_000.0]
    assert fin.diluted_eps == [7.46, 6.08, 6.13]   # EPS value row not misread as count


def test_diluted_shares_prefers_weighted_average_over_component_line():
    # A stray "diluted shares from <X>" component line precedes the real weighted-avg
    # row; the canonical row must win despite the component appearing first.
    df = _income_df()
    fy = {"2025-09-27 (FY)": 1.0, "2024-09-28 (FY)": 1.0, "2023-09-30 (FY)": 1.0}
    component = {"concept": "x", "label": "Dilutive effect of diluted shares from convertible notes",
                 "standard_concept": float("nan"), "level": 3, "abstract": False, **fy}
    canonical = {"concept": "us-gaap_WeightedAverageNumberOfDilutedSharesOutstanding",
                 "label": "Weighted average shares outstanding, diluted",
                 "standard_concept": float("nan"), "level": 2, "abstract": False,
                 "2025-09-27 (FY)": 15_000_000_000.0, "2024-09-28 (FY)": 15_400_000_000.0,
                 "2023-09-30 (FY)": 15_800_000_000.0}
    df = pd.concat([df, pd.DataFrame([component, canonical])], ignore_index=True)
    fin = extract_financials(df, _cashflow_df(), pd.DataFrame(), shares_diluted=None)
    assert fin.diluted_shares == [15_000_000_000.0, 15_400_000_000.0, 15_800_000_000.0]


def test_extract_aligns_series_newest_first():
    fin = extract_financials(_income_df(), _cashflow_df(), pd.DataFrame(), shares_diluted=15_004_697_000.0)
    assert fin.fiscal_period_end == ["2025-09-27", "2024-09-28", "2023-09-30"]
    assert fin.operating_cash_flow == [111_482_000_000.0, 118_254_000_000.0, 110_543_000_000.0]
    assert fin.free_cash_flow == [pytest.approx(98_767_000_000.0), pytest.approx(108_807_000_000.0), pytest.approx(99_584_000_000.0)]
    assert fin.revenue == [416_161_000_000.0, 391_035_000_000.0, 383_285_000_000.0]
    assert fin.net_income == [112_010_000_000.0, 93_736_000_000.0, 96_995_000_000.0]
    assert fin.diluted_eps == [7.46, 6.08, 6.13]


def test_eps_falls_back_to_net_income_over_shares_when_row_missing():
    inc = _income_df()
    inc = inc[inc["label"] != "Diluted (in dollars per share)"]
    fin = extract_financials(inc, _cashflow_df(), pd.DataFrame(), shares_diluted=15_004_697_000.0)
    assert fin.diluted_eps[0] == pytest.approx(112_010_000_000.0 / 15_004_697_000.0, rel=1e-3)


def test_eps_empty_when_no_row_and_no_shares():
    inc = _income_df()
    inc = inc[inc["label"] != "Diluted (in dollars per share)"]
    fin = extract_financials(inc, _cashflow_df(), pd.DataFrame(), shares_diluted=None)
    assert fin.diluted_eps == []


def test_missing_concepts_yield_empty_lists_not_crash():
    empty = pd.DataFrame([{"standard_concept": "SomethingElse", "label": "x", "2025-09-27 (FY)": 1.0}])
    fin = extract_financials(empty, empty, pd.DataFrame(), shares_diluted=None)
    assert fin.revenue == []
    assert fin.free_cash_flow == []
    assert fin.diluted_eps == []


def test_no_financials_at_all_returns_empty_dataclass():
    empty = pd.DataFrame()
    fin = extract_financials(empty, empty, pd.DataFrame(), shares_diluted=None)
    assert fin == EdgarFinancials()


def test_series_with_pd_na_returns_empty():
    # nullable-int dtype cells (pd.NA) must degrade to [], not raise TypeError.
    df = pd.DataFrame([{"standard_concept": "Revenue", "label": "r",
                        "2025-09-27 (FY)": pd.NA, "2024-09-28 (FY)": 100.0}])
    fin = extract_financials(df, df, pd.DataFrame(), shares_diluted=None)
    assert fin.revenue == []


def test_operating_cf_picks_subtotal_not_breakdown_child():
    # Real edgartools output attributes the section's standard_concept to nested
    # working-capital CHILD rows too (e.g. MSFT: "Other long-term assets" carries
    # standard_concept=NetCashFromOperatingActivities at level 4). The true subtotal
    # ("Net cash from operations") is the LEAST-nested matching row. Picking the
    # first match (a child) silently corrupts OCF -> FCF collapses to ~-capex.
    cashflow = pd.DataFrame([
        {"concept": "us-gaap_IncreaseDecreaseInOtherNoncurrentAssets", "label": "Other long-term assets",
         "standard_concept": "NetCashFromOperatingActivities", "level": 4, "abstract": False,
         "2025-06-30 (FY)": -2_950_000_000.0, "2024-06-30 (FY)": -6_817_000_000.0},
        {"concept": "us-gaap_NetCashProvidedByUsedInOperatingActivities", "label": "Net cash from operations",
         "standard_concept": "NetCashFromOperatingActivities", "level": 2, "abstract": False,
         "2025-06-30 (FY)": 136_162_000_000.0, "2024-06-30 (FY)": 118_548_000_000.0},
        {"concept": "us-gaap_PaymentsToAcquirePropertyPlantAndEquipment", "label": "Additions to PP&E",
         "standard_concept": "CapitalExpenses", "level": 3, "abstract": False,
         "2025-06-30 (FY)": -64_551_000_000.0, "2024-06-30 (FY)": -44_477_000_000.0},
    ])
    fin = extract_financials(_income_df(), cashflow, pd.DataFrame(), shares_diluted=None)
    assert fin.operating_cash_flow == [136_162_000_000.0, 118_548_000_000.0]
    assert fin.free_cash_flow == [pytest.approx(71_611_000_000.0), pytest.approx(74_071_000_000.0)]


def test_capex_ignores_noncash_supplemental_disclosure_row():
    # GOOGL tags a non-cash supplemental note ("capex incurred but not yet paid",
    # a POSITIVE accrual) as CapitalExpenses. It sits under a Noncash...Disclosure
    # parent abstract and is shallower (level 2) than the real cash payment (level
    # 3) -- so a naive min-level pick would choose it and make FCF exceed OCF.
    cashflow = pd.DataFrame([
        {"concept": "us-gaap_NetCashProvidedByUsedInOperatingActivities", "label": "Net cash from operations",
         "standard_concept": "NetCashFromOperatingActivities", "level": 2, "abstract": False,
         "parent_abstract_concept": "us-gaap_CashCashEquivalents...PeriodIncreaseDecrease...",
         "2025-12-31 (FY)": 164_713_000_000.0},
        {"concept": "us-gaap_PaymentsToAcquirePropertyPlantAndEquipment", "label": "Purchases of PP&E",
         "standard_concept": "CapitalExpenses", "level": 3, "abstract": False,
         "parent_abstract_concept": "us-gaap_NetCashProvidedByUsedInInvestingActivitiesAbstract",
         "2025-12-31 (FY)": -91_447_000_000.0},
        {"concept": "us-gaap_CapitalExpendituresIncurredButNotYetPaid", "label": "Capex accrued",
         "standard_concept": "CapitalExpenses", "level": 2, "abstract": False,
         "parent_abstract_concept": "us-gaap_CashFlowNoncashInvestingAndFinancingActivitiesDisclosureAbstract",
         "2025-12-31 (FY)": 15_090_000_000.0},
    ])
    fin = extract_financials(_income_df(), cashflow, pd.DataFrame(), shares_diluted=None)
    assert fin.operating_cash_flow == [164_713_000_000.0]
    assert fin.free_cash_flow == [pytest.approx(73_266_000_000.0)]  # 164.713B - 91.447B, never > OCF


def test_fy_columns_detected_by_suffix_and_sorted_desc():
    df = pd.DataFrame([{"standard_concept": "Revenue", "label": "r", "concept": "x", "level": 0, "abstract": False,
                        "2023-09-30 (FY)": 1.0, "2025-09-27 (FY)": 3.0, "2024-09-28 (FY)": 2.0}])
    fin = extract_financials(df, df, pd.DataFrame(), shares_diluted=None)
    assert fin.revenue == [3.0, 2.0, 1.0]
