# tests/test_edgar_facts.py
import pandas as pd
import pytest

from shortlist.providers._edgar_facts import extract_financials, EdgarFinancials


def _cashflow_df():
    # Faithful mirror of edgartools cashflow_statement().to_dataframe(): includes the
    # non-FY columns (concept/label/level/abstract) and ABSOLUTE-USD values, newest FY first.
    return pd.DataFrame([
        {"concept": "us-gaap_NetCashProvided...", "label": "Cash generated by operating activities",
         "standard_concept": "NetCashFromOperatingActivities", "level": 1, "abstract": False,
         "2025-09-27 (FY)": 111_482_000_000.0, "2024-09-28 (FY)": 118_254_000_000.0, "2023-09-30 (FY)": 110_543_000_000.0},
        {"concept": "us-gaap_PaymentsToAcquire...", "label": "Payments for acquisition of PP&E",
         "standard_concept": "CapitalExpenses", "level": 2, "abstract": False,
         "2025-09-27 (FY)": -12_715_000_000.0, "2024-09-28 (FY)": -9_447_000_000.0, "2023-09-30 (FY)": -10_959_000_000.0},
    ])


def _income_df():
    return pd.DataFrame([
        {"concept": "us-gaap_Revenue", "label": "Net sales", "standard_concept": "Revenue", "level": 0, "abstract": False,
         "2025-09-27 (FY)": 416_161_000_000.0, "2024-09-28 (FY)": 391_035_000_000.0, "2023-09-30 (FY)": 383_285_000_000.0},
        {"concept": "us-gaap_NetIncomeLoss", "label": "Net income", "standard_concept": "NetIncomeLoss", "level": 0, "abstract": False,
         "2025-09-27 (FY)": 112_010_000_000.0, "2024-09-28 (FY)": 93_736_000_000.0, "2023-09-30 (FY)": 96_995_000_000.0},
        {"concept": float("nan"), "label": "Diluted (in dollars per share)", "standard_concept": float("nan"), "level": 2, "abstract": False,
         "2025-09-27 (FY)": 7.46, "2024-09-28 (FY)": 6.08, "2023-09-30 (FY)": 6.13},
    ])


def test_extract_aligns_series_newest_first():
    fin = extract_financials(_income_df(), _cashflow_df(), shares_diluted=15_004_697_000.0)
    assert fin.fiscal_period_end == ["2025-09-27", "2024-09-28", "2023-09-30"]
    assert fin.operating_cash_flow == [111_482_000_000.0, 118_254_000_000.0, 110_543_000_000.0]
    assert fin.free_cash_flow == [pytest.approx(98_767_000_000.0), pytest.approx(108_807_000_000.0), pytest.approx(99_584_000_000.0)]
    assert fin.revenue == [416_161_000_000.0, 391_035_000_000.0, 383_285_000_000.0]
    assert fin.net_income == [112_010_000_000.0, 93_736_000_000.0, 96_995_000_000.0]
    assert fin.diluted_eps == [7.46, 6.08, 6.13]


def test_eps_falls_back_to_net_income_over_shares_when_row_missing():
    inc = _income_df()
    inc = inc[inc["label"] != "Diluted (in dollars per share)"]
    fin = extract_financials(inc, _cashflow_df(), shares_diluted=15_004_697_000.0)
    assert fin.diluted_eps[0] == pytest.approx(112_010_000_000.0 / 15_004_697_000.0, rel=1e-3)


def test_eps_empty_when_no_row_and_no_shares():
    inc = _income_df()
    inc = inc[inc["label"] != "Diluted (in dollars per share)"]
    fin = extract_financials(inc, _cashflow_df(), shares_diluted=None)
    assert fin.diluted_eps == []


def test_missing_concepts_yield_empty_lists_not_crash():
    empty = pd.DataFrame([{"standard_concept": "SomethingElse", "label": "x", "2025-09-27 (FY)": 1.0}])
    fin = extract_financials(empty, empty, shares_diluted=None)
    assert fin.revenue == []
    assert fin.free_cash_flow == []
    assert fin.diluted_eps == []


def test_no_financials_at_all_returns_empty_dataclass():
    empty = pd.DataFrame()
    fin = extract_financials(empty, empty, shares_diluted=None)
    assert fin == EdgarFinancials()


def test_fy_columns_detected_by_suffix_and_sorted_desc():
    df = pd.DataFrame([{"standard_concept": "Revenue", "label": "r", "concept": "x", "level": 0, "abstract": False,
                        "2023-09-30 (FY)": 1.0, "2025-09-27 (FY)": 3.0, "2024-09-28 (FY)": 2.0}])
    fin = extract_financials(df, df, shares_diluted=None)
    assert fin.revenue == [3.0, 2.0, 1.0]
